CREATE TABLE IF NOT EXISTS automations (
  id text PRIMARY KEY,
  wallet_address text NOT NULL,
  network text NOT NULL,
  type text NOT NULL,
  status text NOT NULL,
  expected_policy_id_hex text NOT NULL,
  onchain_policy_id_hex text,
  session_creation_tx_hash text,
  delegate_public_key_ciphertext text NOT NULL,
  delegate_public_key_iv text NOT NULL,
  delegate_public_key_tag text NOT NULL,
  delegate_private_key_ciphertext text NOT NULL,
  delegate_private_key_iv text NOT NULL,
  delegate_private_key_tag text NOT NULL,
  encryption_version integer NOT NULL,
  policy_input_json jsonb NOT NULL,
  policy_input_xdr_base64 text NOT NULL,
  delegate_pop_hex text NOT NULL,
  delegate_pop_xdr_base64 text NOT NULL,
  strategy_json jsonb NOT NULL,
  schedule_json jsonb NOT NULL,
  valid_after_ledger bigint NOT NULL,
  expires_at_ledger bigint NOT NULL,
  max_uses integer,
  run_count integer NOT NULL DEFAULT 0,
  spent_amount numeric NOT NULL DEFAULT 0,
  agenda_job_id text,
  payment_status text NOT NULL,
  payment_amount text NOT NULL,
  payment_asset text NOT NULL,
  payment_network text NOT NULL,
  payment_treasury text NOT NULL,
  payment_quote_expires_at timestamptz NOT NULL,
  payment_tx_hash text,
  payment_payer text,
  payment_session_id text,
  payment_payload_hash text,
  next_run_at timestamptz,
  last_run_at timestamptz,
  last_finished_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  activated_at timestamptz,
  revoked_at timestamptz,
  last_error text
);

CREATE TABLE IF NOT EXISTS payment_sessions (
  id text PRIMARY KEY,
  automation_id text NOT NULL REFERENCES automations(id),
  payer_address text NOT NULL,
  network text NOT NULL,
  asset_contract text NOT NULL,
  treasury_address text NOT NULL,
  amount text NOT NULL,
  args_xdr jsonb NOT NULL,
  expires_at_ledger bigint NOT NULL,
  quote_expires_at timestamptz NOT NULL,
  status text NOT NULL,
  signed_auth_hash text,
  transaction_hash text,
  error text,
  settled_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS automation_runs (
  id text PRIMARY KEY,
  automation_id text NOT NULL REFERENCES automations(id),
  idempotency_key text NOT NULL UNIQUE,
  status text NOT NULL,
  scheduled_for timestamptz NOT NULL,
  transaction_hash text,
  response_json jsonb,
  error text,
  completed_at timestamptz
);
